services:
  - type: web
    name: bpo-connect-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /index.html
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://bpo-connect-liart.vercel.app,http://localhost:8080
      - key: JPA_DDL_AUTO
        value: update
